services:
  app:
    build:
      context: .
      args:
      - MAVEN_OPTS=-Dmaven.test.skip=true -DskipTests=true
      dockerfile: Dockerfile
    environment:
    - JAVA_OPTS=-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005
    ports:
    - "8080:8080"
    - "5005:5005"
    depends_on:
    - postgres
    - mysql
#    healthcheck:
#      test: wget --no-verbose --tries=1 --spider http://localhost:8080//api/actuator/health || exit 1
#      interval: 5s
#      retries: 60
#      start_period: 30s
#      timeout: 30s

  postgres:
    image: postgres:15.2
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
    - "5432:5432"
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
    - ./postgres/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh:ro

  mysql:
    image: mariadb:10.3.8
    command:
    - --default-authentication-plugin=mysql_native_password --skip_name_resolve
    - --bind-address=0.0.0.0
    container_name: mysql
    restart: unless-stopped
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"
